### PR TITLE
Added danish translations.

### PR DESCRIPTION
**Pull request by jstoone**
First version of Danish translations. 

I figured I wouldn't translate the comments, I hope you don't mind. :)

### CODE REVIEW

**Comment by ericlbarnes** [comment]
Thanks! :+1:

**Comment by jstoone** [comment]
You are very welcome! :smiley:
It's my first of many pull requests to wardrobecms!

**Comment by ericlbarnes** [comment]
Awesome. If you haven't seen it I've been working on v2 and if you are interested in following along I write about it each week - http://ericlbarnes.com/wardrobe-diaries/

**Comment by jstoone** [comment]
This is really good! 

Looking forward to see your progress.

On Thursday, Sep 18, 2014 at 3:25 am, Eric Barnes notifications@github.com, wrote:
Awesome. If you haven't seen it I've been working on v2 and if you are interested in following along I write about it each week - http://ericlbarnes.com/wardrobe-diaries/

**Pull request merged**
